- hosts: tomcatserver
  become: true
  vars:
    url_name: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
    tomcat_url_name: https://downloads.apache.org/tomcat/tomcat-9/v9.0.112/bin/apache-tomcat-9.0.112.tar.gz.sha512
  tasks:
    - name: Download JAVA
      ansible.builtin.get_url:
        url: "{{ url_name }}"
        dest: /opt/openjdk-11.0.2_linux-x64_bin.tar.gz
      tags:
        - Download_java
    - name: Unzip a file on remote host
      ansible.builtin.unarchive:
        src: /opt/openjdk-11.0.2_linux-x64_bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Move folder from jdk-11.0.2 to java-11
      ansible.builtin.command:
        cmd: mv /opt/jdk-11.0.2 /opt/java-11
    - name: Create symlink for java
      ansible.builtin.file:
        src: /opt/java-11/bin/java
        dest: /usr/bin/java
        state: link
    - name: Set JAVA_HOME 
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: 'export JAVA_HOME-=/opt/java-11'
        state: present
    - name: echo java_home path
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: 'export PATH=$PATH:$JAVA_HOME/bin'
        state: present
    - name: Reload /etc/profile
      ansible.builtin.shell: 
        source /etc/profile
    - name: remove tar,gz file.
      ansible.builtin.file:
        path: /opt/openjdk-11.0.2_linux-x64_bin.tar.gz
        state: absent
    - name: Verify Java installation
      ansible.builtin.command: java -version
      register: java_version
      ignore_errors: yes
    - debug:
        var: java_version.stderr 
    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "{{ tomcat_url_name }}"
        dest: /opt/apache-tomcat-9.0.112.tar.gz
      tags:
        - Download_Tomcat
    - name: Unzip a file on remote host
      ansible.builtin.unarchive:
        src: /opt/apache-tomcat-9.0.112.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Move folder from tomcat folder
      ansible.builtin.command:
        cmd: mv /opt/apache-tomcat-9.0.112.tar.gz /opt/tomcat
    - name: remove tomcat tar,gz file
      ansible.builtin.file:
        src: /opt/apache-tomcat-9.0.112.tar.gz
        state: absent

